Using base prefix '/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5'
New python executable in /home/ydamergi/venvs/venv-for-python/bin/python3.7
Also creating executable in /home/ydamergi/venvs/venv-for-python/bin/python
Traceback (most recent call last):
  File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==16.7.6', 'console_scripts', 'virtualenv')()
  File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages/virtualenv.py", line 1156, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages/virtualenv.py", line 1666, in install_python
    os.symlink(py_executable_base, full_pth)
FileExistsError: [Errno 17] File exists: 'python3.7' -> '/home/ydamergi/venvs/venv-for-python/bin/python'
Requirement already satisfied: xlrd==1.2.0 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (1.2.0)
Requirement already satisfied: numpy in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (1.18.5)
Requirement already satisfied: matplotlib in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (3.2.2)
Requirement already satisfied: cycler>=0.10 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: numpy>=1.11 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from matplotlib) (1.18.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: python-dateutil>=2.1 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from matplotlib) (2.8.0)
Requirement already satisfied: six in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from cycler>=0.10->matplotlib) (1.14.0)
Requirement already satisfied: setuptools in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (65.3.0)
ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools
Traceback (most recent call last):
  File "/home/ydamergi/venvs/venv-for-python/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_internal/exceptions.py", line 13, in <module>
    from pip._vendor.requests.models import Request, Response
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_vendor/urllib3/__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 12, in <module>
    from .connection import (
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 15, in <module>
    from .util.proxy import create_proxy_ssl_context
  File "/home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages/pip/_vendor/urllib3/util/__init__.py", line 20, in <module>
    from .timeout import Timeout, current_time
ModuleNotFoundError: No module named 'pip._vendor.urllib3.util.timeout'
Requirement already satisfied: sklearn in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (0.0)
Requirement already satisfied: scikit-learn in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from sklearn) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.18.5)
Requirement already satisfied: scipy>=1.1.0 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.5.0)
ERROR: Could not find a version that satisfies the requirement import (from versions: none)
ERROR: No matching distribution found for import
ERROR: Could not find a version that satisfies the requirement import (from versions: none)
ERROR: No matching distribution found for import
ERROR: Could not find a version that satisfies the requirement import (from versions: none)
ERROR: No matching distribution found for import
ERROR: Could not find a version that satisfies the requirement warnings (from versions: none)
ERROR: No matching distribution found for warnings
Requirement already satisfied: scikit_optimize in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (0.9.0)
Requirement already satisfied: numpy>=1.13.3 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from scikit_optimize) (1.18.5)
Requirement already satisfied: scipy>=0.19.1 in /ssoft/spack/arvine/v1/opt/spack/linux-rhel7-broadwell/gcc-8.4.0/python-3.7.7-oj5bqtdwernlqpzm5gwdliaatkqu47w5/lib/python3.7/site-packages (from scikit_optimize) (1.5.0)
Requirement already satisfied: joblib>=0.11 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit_optimize) (1.1.0)
Requirement already satisfied: pyaml>=16.9 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit_optimize) (21.10.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit_optimize) (1.0.2)
Requirement already satisfied: PyYAML in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from pyaml>=16.9->scikit_optimize) (6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ydamergi/venvs/venv-for-python/lib/python3.7/site-packages (from scikit-learn>=0.20.0->scikit_optimize) (3.1.0)
the number of rows is equal 65 to the number of samples 
the number of columns is equal 200 to the number of genes 
We have  2 different sample classes 
